//go:build !wasm

/*
 * SynapSeq - Text-Driven Audio Sequencer for Brainwave Entrainment
 * https://synapseq.org
 *
 * Copyright (c) 2025-2026 SynapSeq Foundation
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2.
 * See the file COPYING.txt for details.
 */

package spsq

import (
	"strings"
	"testing"
	"time"
)

func TestBuilderBuildPreservesOrder(t *testing.T) {
	builder := New().
		SampleRate(48000).
		Volume(80).
		Ambiance("rain", "rain").
		Ambiance("wind", "wind")

	alpha := builder.NewPreset("alpha")
	alpha.PinkNoise(0).Amplitude(30)

	beta := builder.NewPreset("beta")
	beta.PinkNoise(10).Amplitude(15)

	loaded, err := builder.
		SilenceAt(0).
		At(15*time.Second, alpha).
		At(time.Minute, beta).
		Build()
	if err != nil {
		t.Fatalf("Build error: %v", err)
	}
	content := string(loaded.RawContent())

	expected := strings.Join([]string{
		"# Generated by Synapseq API",
		"",
		"# Options",
		"@samplerate 48000",
		"@volume 80",
		"@ambiance rain rain",
		"@ambiance wind wind",
		"",
		"# Presets",
		"alpha",
		"  noise pink smooth 0.00 amplitude 30.00",
		"beta",
		"  noise pink smooth 10.00 amplitude 15.00",
		"",
		"# Timeline",
		"00:00:00 silence steady 0",
		"00:00:15 alpha steady 0",
		"00:01:00 beta steady 0",
		"",
	}, "\n")

	if content != expected {
		t.Fatalf("unexpected content:\n%s", content)
	}
}

func TestBuilderBuildReturnsValidationError(t *testing.T) {
	builder := New()
	alpha := builder.NewPreset("alpha")
	alpha.Tone(300).Binaural(10).Amplitude(15)

	_, err := builder.At(99*time.Minute, alpha).Build()
	if err == nil {
		t.Fatal("expected validation error")
	}
}
