/*
 * SynapSeq - Text-Driven Audio Sequencer for Brainwave Entrainment
 * https://synapseq.org
 *
 * Copyright (c) 2025-2026 SynapSeq Foundation
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2.
 * See the file COPYING.txt for details.
 */

package spsq

import (
	"fmt"
	"strings"

	t "github.com/synapseq-foundation/synapseq/v4/internal/types"
)

// Timeline constants define the indices of timeline fields
const (
	timelineTime       = 0
	timelinePreset     = 1
	timelineTransition = 2
	timelineStep       = 3
)

// Builder is responsible for building a sequence from a string sequence content
type Builder struct {
	lastPreset string
	extends    []string
	timeline   [][4]string
	ambiance   [][]string
	options    map[string]string
	presets    map[string][]t.Track
}

// New creates a new Builder
func New() *Builder {
	defaultOptions := map[string]string{
		t.KeywordOptionSampleRate: "44100",
		t.KeywordOptionVolume:     "100",
	}

	return &Builder{
		lastPreset: "",
		extends:    make([]string, 0),
		timeline:   make([][4]string, 0),
		ambiance:   make([][]string, 0),
		options:    defaultOptions,
		presets:    make(map[string][]t.Track),
	}
}

// String returns the sequence as a string
func (b *Builder) String() string {
	var content strings.Builder

	cmm := t.KeywordComment
	opt := t.KeywordOption

	fmt.Fprintf(&content, "%s Generated by Synapseq API\n\n", cmm)

	fmt.Fprintf(&content, "%s Options\n", cmm)
	// Common options
	for key, value := range b.options {
		fmt.Fprintf(&content, "%s %s\n", opt+key, value)
	}
	// Ambiance
	for _, ambiance := range b.ambiance {
		fmt.Fprintf(&content, "%s%s %s\n", opt, t.KeywordOptionAmbiance, strings.Join(ambiance, " "))
	}
	// Extends
	for _, extend := range b.extends {
		fmt.Fprintf(&content, "%s%s %s\n", opt, t.KeywordOptionExtends, extend)
	}

	fmt.Fprintf(&content, "\n%s Presets\n", cmm)
	for preset, tracks := range b.presets {
		fmt.Fprintf(&content, "%s\n", preset)
		for _, track := range tracks {
			fmt.Fprintf(&content, "  %s\n", track.String())
		}
	}

	fmt.Fprintf(&content, "\n%s Timeline\n", cmm)
	for _, timeline := range b.timeline {
		fmt.Fprintf(&content, "%s %s %s %s\n", timeline[timelineTime], timeline[timelinePreset], timeline[timelineTransition], timeline[timelineStep])
	}

	return content.String()
}
