/*
 * SynapSeq - Text-Driven Audio Sequencer for Brainwave Entrainment
 * https://synapseq.org
 *
 * Copyright (c) 2025-2026 SynapSeq Foundation
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2.
 * See the file COPYING.txt for details.
 */

package spsq

import (
	"fmt"
	"strings"
	"time"

	synapseq "github.com/synapseq-foundation/synapseq/v4/core"
	t "github.com/synapseq-foundation/synapseq/v4/internal/types"
)

// Builder is responsible for building a sequence from a string sequence content
type Builder struct {
	timeline []timelineEntry
	ambiance []ambianceOption
	options  map[string]string
	presets  []presetEntry
}

// ambianceOption holds the name and path of an ambiance source
type ambianceOption struct {
	name string
	path string
}

// presetEntry holds the name and tracks of a preset.
type presetEntry struct {
	name   string
	tracks []t.Track
}

// timelineEntry holds one generated timeline declaration.
type timelineEntry struct {
	at         time.Duration
	presetName string
	transition string
	steps      int
}

// New creates a new Builder
func New() *Builder {
	return &Builder{
		timeline: make([]timelineEntry, 0),
		ambiance: make([]ambianceOption, 0),
		options:  make(map[string]string),
		presets:  make([]presetEntry, 0),
	}
}

// Build returns a loaded context for the generated .spsq content.
func (b *Builder) Build() (*synapseq.LoadedContext, error) {
	content := b.content()
	return synapseq.NewAppContext().LoadContent(content)
}

// content returns the generated .spsq content as a string.
func (b *Builder) content() string {
	var content strings.Builder

	cmm := t.KeywordComment
	opt := t.KeywordOption

	fmt.Fprintf(&content, "%s Generated by Synapseq API\n\n", cmm)

	fmt.Fprintf(&content, "%s Options\n", cmm)
	if value, ok := b.options[t.KeywordOptionSampleRate]; ok {
		fmt.Fprintf(&content, "%s %s\n", opt+t.KeywordOptionSampleRate, value)
	}
	if value, ok := b.options[t.KeywordOptionVolume]; ok {
		fmt.Fprintf(&content, "%s %s\n", opt+t.KeywordOptionVolume, value)
	}
	for _, ambiance := range b.ambiance {
		fmt.Fprintf(&content, "%s%s %s %s\n", opt, t.KeywordOptionAmbiance, ambiance.name, ambiance.path)
	}

	fmt.Fprintf(&content, "\n%s Presets\n", cmm)
	for _, preset := range b.presets {
		fmt.Fprintf(&content, "%s\n", preset.name)
		for _, track := range preset.tracks {
			fmt.Fprintf(&content, "  %s\n", track.String())
		}
	}

	fmt.Fprintf(&content, "\n%s Timeline\n", cmm)
	for _, timeline := range b.timeline {
		fmt.Fprintf(&content, "%s %s %s %d\n", formatTimelineTime(timeline.at), timeline.presetName, timeline.transition, timeline.steps)
	}

	return content.String()
}
