// Copyright (C) 2026 SynapSeq Contributors
//
// SPDX-License-Identifier: GPL-3.0-or-later

package sbg

import (
	"os"
	"strings"
	"testing"
	"time"
)

func TestConvertedContentPreservesOrder(t *testing.T) {
	t.Chdir(t.TempDir())
	if err := os.WriteFile("music.wav", nil, 0o600); err != nil {
		t.Fatal(err)
	}
	input := "-r 48000 -m music.wav\n" +
		"Beta: - pink/40 200/5 300-10/20 spin:300+4.2/10 mix/25\n" +
		"Alpha: 400/10\noff: -\nNOW+00:00:15 <> Beta ->\n+00:01:00 Alpha\n+00:02:00 off\n"
	want := conversionHeader + "# Generated by Synapseq API\n\n" +
		"# Options\n@samplerate 48000\n@music music\n\n" +
		"# Presets\nbeta\n" +
		"  noise pink smooth 0.00 amplitude left 40.00 right 40.00\n" +
		"  waveform sine tone 200.00 amplitude left 5.00 right 5.00\n" +
		"  waveform sine tone 300.00 binaural 10.00 amplitude left 20.00 right 20.00\n" +
		"  noise pink smooth 0.00 effect pan 4.20 intensity 100.00 amplitude left 10.00 right 10.00\n" +
		"  waveform sine music music amplitude left 25.00 right 25.00\n" +
		"alpha\n  waveform sine tone 400.00 amplitude left 10.00 right 10.00\n\n" +
		"# Timeline\n00:00:00 silence steady 0\n00:00:15 beta steady 0\n" +
		"00:01:15 alpha steady 0\n00:02:15 silence steady 0\n"
	loaded, err := newTestConverter(t).LoadContent(input)
	if err != nil {
		t.Fatal(err)
	}
	if got := string(loaded.RawContent()); got != want {
		t.Fatalf("converted content:\n%s\nwant:\n%s", got, want)
	}
}

func TestConvertedTimelineCompatibility(t *testing.T) {
	tests := []struct {
		name  string
		input string
		want  string
	}{
		{
			name:  "now",
			input: "NOW alpha\n+00:01:00 off",
			want:  "00:00:00 silence steady 0\n00:00:30 alpha steady 0\n00:01:00 silence steady 0\n",
		},
		{
			name:  "now offset",
			input: "NOW+00:00:15 alpha\n+00:01:00 off",
			want:  "00:00:00 silence steady 0\n00:00:15 alpha steady 0\n00:01:15 silence steady 0\n",
		},
		{
			name:  "absolute base",
			input: "01:00:00 alpha\n01:01:00 off",
			want:  "00:00:00 alpha steady 0\n00:01:00 silence steady 0\n",
		},
		{
			name:  "initial silence",
			input: "NOW off\n+00:01:00 alpha\n+00:02:00 off",
			want:  "00:00:00 silence steady 0\n00:01:00 alpha steady 0\n00:02:00 silence steady 0\n",
		},
	}
	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			loaded, err := newTestConverter(t).LoadContent("alpha: 200/10\noff: -\n" + test.input)
			if err != nil {
				t.Fatal(err)
			}
			want := conversionHeader + "# Generated by Synapseq API\n\n# Options\n@samplerate 44100\n\n" +
				"# Presets\nalpha\n  waveform sine tone 200.00 amplitude left 10.00 right 10.00\n\n# Timeline\n" + test.want
			if got := string(loaded.RawContent()); got != want {
				t.Fatalf("converted content = %q, want %q", got, want)
			}
		})
	}
}

func TestParseRelativeTimesUseLastAbsoluteBase(t *testing.T) {
	input := "alpha: 200/10\n01:00:00 alpha\n+00:00:10 alpha\n+00:00:20 alpha\n02:00:00 alpha\n+00:00:05 alpha"
	sequence, err := parse("test.sbg", strings.NewReader(input))
	if err != nil {
		t.Fatal(err)
	}
	want := []time.Duration{
		time.Hour,
		time.Hour + 10*time.Second,
		time.Hour + 20*time.Second,
		2 * time.Hour,
		2*time.Hour + 5*time.Second,
	}
	if len(sequence.timeline) != len(want) {
		t.Fatalf("timeline has %d entries, want %d", len(sequence.timeline), len(want))
	}
	for index, event := range sequence.timeline {
		if event.at != want[index] {
			t.Fatalf("event %d = %v, want %v", index, event.at, want[index])
		}
	}
}

func TestParseOptionAndIgnoredLineCompatibility(t *testing.T) {
	input := "# comment\r\nignored text\n_bad: nonsense\n" +
		"-m first.wav -m ignored.wav -r 22050 -r 96000\n" +
		"unused: -m final.wav -r 48000 -r invalid\nalpha: 200/10 # comment\nNOW alpha\n"
	sequence, err := parse("test.sbg", strings.NewReader(input))
	if err != nil {
		t.Fatal(err)
	}
	if sequence.musicPath != "final.wav" || sequence.musicLine != 5 || sequence.sampleRate != 48000 {
		t.Fatalf("options = %#v", sequence)
	}
	if len(sequence.definitions) != 1 || sequence.definitions[0].name != "alpha" {
		t.Fatalf("definitions = %#v", sequence.definitions)
	}
	input = "-m first.wav -m ignored.wav -r 22050 -r invalid\nalpha: 200/10\nNOW alpha"
	sequence, err = parse("test.sbg", strings.NewReader(input))
	if err != nil {
		t.Fatal(err)
	}
	if sequence.musicPath != "first.wav" || sequence.sampleRate != 22050 {
		t.Fatalf("first options on a line must win: %#v", sequence)
	}
}

func TestConversionErrorCompatibility(t *testing.T) {
	tests := []struct {
		name  string
		input string
		want  string
	}{
		{
			name:  "duplicate before voice",
			input: "alpha: 200/10\nalpha: invalid",
			want:  `parse "<content>" line 2: duplicate NameDef "alpha"`,
		},
		{
			name:  "music before rate",
			input: "-r invalid -m",
			want:  `parse "<content>" line 1: -m requires an audio file`,
		},
		{
			name:  "missing rate",
			input: "-r",
			want:  `parse "<content>" line 1: -r requires a sample rate`,
		},
		{
			name:  "invalid rate",
			input: "-r invalid",
			want:  `parse "<content>" line 1: -r requires an integer sample rate`,
		},
		{
			name:  "empty definition",
			input: "alpha:",
			want:  `parse "<content>" line 1: NameDef "alpha" has no voices`,
		},
		{
			name:  "bare mix",
			input: "alpha: mix",
			want:  `parse "<content>" line 1: voice "mix": unexpected character 'm'`,
		},
		{
			name:  "missing music",
			input: "alpha: mix/10\nNOW alpha",
			want:  `parse "<content>" line 1: mix voice requires a -m music source`,
		},
		{
			name:  "unknown reference",
			input: "alpha: 200/10\nNOW missing",
			want:  `parse "<content>" line 2: timeline references undefined NameDef "missing"`,
		},
		{
			name:  "nul in comment",
			input: "# ignored\x00",
			want:  `parse "<content>" line 1: NUL byte is not allowed`,
		},
		{
			name:  "no definitions",
			input: "ignored",
			want:  `parse "<content>": no NameDefs found`,
		},
		{
			name:  "no timeline",
			input: "alpha: 200/10",
			want:  `parse "<content>": no timeline entries found`,
		},
		{
			name:  "equal events",
			input: "alpha: 200/10\n00:00 alpha\n00:00 alpha",
			want:  `parse "<content>" line 3: timeline entries must be strictly increasing`,
		},
		{
			name:  "decreasing events",
			input: "alpha: 200/10\n00:10 alpha\n00:05 alpha",
			want:  `parse "<content>" line 3: timeline entries must be strictly increasing`,
		},
		{
			name:  "now interval",
			input: "alpha: 200/10\nNOW alpha\n+00:00:20 alpha",
			want:  `parse "<content>" line 3: timeline entries must be strictly increasing`,
		},
		{
			name:  "initial off interval",
			input: "off: -\nNOW off\n+00:00:20 off",
			want:  `parse "<content>" line 3: timeline entries must be strictly increasing`,
		},
		{
			name:  "remote music",
			input: "-m https://example.com/music.wav\nalpha: mix/10\nNOW alpha",
			want:  `parse "<content>" line 1: music source must be a local path`,
		},
		{
			name:  "parent music",
			input: "-m audio/../music.wav\nalpha: mix/10\nNOW alpha",
			want:  `parse "<content>" line 1: music source must not contain parent directory traversal`,
		},
		{
			name:  "backslash music",
			input: "-m audio\\music.wav\nalpha: mix/10\nNOW alpha",
			want:  `parse "<content>" line 1: music source must use '/' path separators`,
		},
	}
	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			_, err := newTestConverter(t).LoadContent(test.input)
			if err == nil || err.Error() != test.want {
				t.Fatalf("error = %v, want %s", err, test.want)
			}
		})
	}
}
