// Copyright (C) 2026 SynapSeq Contributors
//
// SPDX-License-Identifier: GPL-3.0-or-later

package sbg

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	synapseq "github.com/synapseq-foundation/synapseq/v4/core"
)

func newTestConverter(t *testing.T) *Converter {
	t.Helper()
	converter, err := New(synapseq.NewAppContext())
	if err != nil {
		t.Fatalf("New error: %v", err)
	}
	return converter
}

func TestNewRejectsNilContext(t *testing.T) {
	converter, err := New(nil)
	if err == nil {
		t.Fatalf("expected error, got converter %#v", converter)
	}
}

func TestLoadFileUsesSPSQBuilder(t *testing.T) {
	dir := t.TempDir()
	t.Chdir(dir)
	if err := os.Mkdir("audio", 0o755); err != nil {
		t.Fatalf("create audio directory: %v", err)
	}
	musicPath := filepath.Join(dir, "audio", "background.mp3")
	if err := os.WriteFile(musicPath, nil, 0o600); err != nil {
		t.Fatalf("write music: %v", err)
	}
	inputPath := filepath.Join(dir, "session.sbg")
	input := strings.Join([]string{
		"-m " + musicPath,
		"Alpha.Long.Name: pink/40 300+10/20 spin:300+4.2/10 mix/25",
		"alloff: -",
		"NOW+00:00:15 <> Alpha.Long.Name ->",
		"+00:01:00 == alloff",
	}, "\n")
	if err := os.WriteFile(inputPath, []byte(input), 0o600); err != nil {
		t.Fatalf("write input: %v", err)
	}

	loaded, err := newTestConverter(t).LoadFile(inputPath)
	if err != nil {
		t.Fatalf("LoadFile error: %v", err)
	}
	text := string(loaded.RawContent())
	checks := []string{
		"# Generated by Synapseq API",
		"@music background audio/background",
		"alpha-long-name",
		"music background amplitude 25.00",
		"noise pink smooth 0.00 amplitude 40.00",
		"tone 300.00 binaural 10.00 amplitude 20.00",
		"noise pink smooth 0.00 effect pan 4.20 intensity 100.00 amplitude 10.00",
		"00:00:00 silence steady 0",
		"00:00:15 alpha-long-name steady 0",
		"00:01:15 silence steady 0",
	}
	for _, check := range checks {
		if !strings.Contains(text, check) {
			t.Errorf("converted content missing %q:\n%s", check, text)
		}
	}
}

func TestLoadFileNOWUsesThirtySecondFadeIn(t *testing.T) {
	dir := t.TempDir()
	inputPath := filepath.Join(dir, "session.sbg")
	input := "alpha: 300+10/20\noff: -\nNOW alpha\n+00:01:00 off\n"
	if err := os.WriteFile(inputPath, []byte(input), 0o600); err != nil {
		t.Fatalf("write input: %v", err)
	}

	loaded, err := newTestConverter(t).LoadFile(inputPath)
	if err != nil {
		t.Fatalf("LoadFile error: %v", err)
	}
	if !strings.Contains(string(loaded.RawContent()), "00:00:30 alpha steady 0") {
		t.Fatalf("missing 30-second fade-in:\n%s", loaded.RawContent())
	}
}

func TestLoadContentSupportsAbsoluteTimelineTimes(t *testing.T) {
	input := strings.Join([]string{
		"off: -",
		"ts1: pink/60 750+15/8 500+10/4 350+7/0 100+2/0",
		"ts2: pink/60 750+14/0 500+9/8 350+6/6 100+2/8",
		"00:00:00 off ->",
		"00:00:15 ts1 ->",
		"00:20:00 ts2 ->",
		"00:20:30 off",
	}, "\n")
	loaded, err := newTestConverter(t).LoadContent(input)
	if err != nil {
		t.Fatalf("LoadContent error: %v", err)
	}
	for _, expected := range []string{
		"00:00:00 silence steady 0",
		"00:00:15 ts1 steady 0",
		"00:20:00 ts2 steady 0",
		"00:20:30 silence steady 0",
	} {
		if !strings.Contains(string(loaded.RawContent()), expected) {
			t.Errorf("converted content missing %q:\n%s", expected, loaded.RawContent())
		}
	}
}

func TestLoadContentRejectsMixWithoutMusicSource(t *testing.T) {
	_, err := newTestConverter(t).LoadContent("alpha: pink/20 mix/20\noff: -\nNOW alpha\n+00:01:00 off\n")
	if err == nil || !strings.Contains(err.Error(), "mix voice requires a -m music source") {
		t.Fatalf("error = %v", err)
	}
}

func TestLoadContentRejectsMusicPathOutsideCurrentDirectory(t *testing.T) {
	dir := t.TempDir()
	t.Chdir(dir)
	outsidePath := filepath.Join(filepath.Dir(dir), "music.mp3")
	input := "-m " + outsidePath + "\nalpha: mix/20\nNOW alpha\n"

	_, err := newTestConverter(t).LoadContent(input)
	if err == nil || !strings.Contains(err.Error(), "inside the current directory") {
		t.Fatalf("error = %v", err)
	}
}

func TestLoadContentRejectsMusicPathWithParentTraversal(t *testing.T) {
	dir := t.TempDir()
	t.Chdir(dir)
	input := "-m audio/../music.mp3\nalpha: mix/20\nNOW alpha\n"

	_, err := newTestConverter(t).LoadContent(input)
	if err == nil || !strings.Contains(err.Error(), "must not contain parent directory traversal") {
		t.Fatalf("error = %v", err)
	}
}

func TestLoadContentDelegatesUnknownMusicExtensionToSPSQ(t *testing.T) {
	dir := t.TempDir()
	t.Chdir(dir)
	if err := os.WriteFile(filepath.Join(dir, "music.ogg"), nil, 0o600); err != nil {
		t.Fatalf("write music: %v", err)
	}

	_, err := newTestConverter(t).LoadContent("-m music.ogg\nalpha: mix/20\nNOW alpha\n")
	if err == nil || !strings.Contains(err.Error(), "music file not found") {
		t.Fatalf("error = %v", err)
	}
}

func TestLoadContentConvertsWAVMusicSource(t *testing.T) {
	dir := t.TempDir()
	t.Chdir(dir)
	if err := os.WriteFile(filepath.Join(dir, "music.wav"), nil, 0o600); err != nil {
		t.Fatalf("write music: %v", err)
	}

	loaded, err := newTestConverter(t).LoadContent("-m music.wav\nalpha: mix/20\nNOW alpha\n")
	if err != nil {
		t.Fatalf("LoadContent error: %v", err)
	}
	if !strings.Contains(string(loaded.RawContent()), "@music music\n") {
		t.Fatalf("music source was not converted:\n%s", loaded.RawContent())
	}
}
