// Copyright (C) 2026 SynapSeq Contributors
//
// SPDX-License-Identifier: GPL-3.0-or-later

package sbg

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestLoadFileUsesSPSQBuilder(t *testing.T) {
	dir := t.TempDir()
	inputPath := filepath.Join(dir, "session.sbg")
	input := strings.Join([]string{
		"-m audio/background.mp3",
		"Alpha.Long.Name: pink/40 300+10/20 spin:300+4.2/10 mix/25",
		"alloff: -",
		"NOW+00:00:15 <> Alpha.Long.Name ->",
		"+00:01:00 == alloff",
	}, "\n")
	if err := os.WriteFile(inputPath, []byte(input), 0o600); err != nil {
		t.Fatalf("write input: %v", err)
	}

	loaded, err := LoadFile(inputPath)
	if err != nil {
		t.Fatalf("LoadFile error: %v", err)
	}
	text := string(loaded.RawContent())
	checks := []string{
		"# Generated by Synapseq API",
		"alpha-long-name",
		"noise pink smooth 0.00 amplitude 40.00",
		"tone 300.00 binaural 10.00 amplitude 20.00",
		"noise pink smooth 0.00 effect pan 4.20 intensity 100.00 amplitude 10.00",
		"00:00:00 silence steady 0",
		"00:00:15 alpha-long-name steady 0",
		"00:01:15 silence steady 0",
	}
	for _, check := range checks {
		if !strings.Contains(text, check) {
			t.Errorf("converted content missing %q:\n%s", check, text)
		}
	}
}

func TestLoadFileNOWUsesThirtySecondFadeIn(t *testing.T) {
	dir := t.TempDir()
	inputPath := filepath.Join(dir, "session.sbg")
	input := "alpha: 300+10/20\noff: -\nNOW alpha\n+00:01:00 off\n"
	if err := os.WriteFile(inputPath, []byte(input), 0o600); err != nil {
		t.Fatalf("write input: %v", err)
	}

	loaded, err := LoadFile(inputPath)
	if err != nil {
		t.Fatalf("LoadFile error: %v", err)
	}
	if !strings.Contains(string(loaded.RawContent()), "00:00:30 alpha steady 0") {
		t.Fatalf("missing 30-second fade-in:\n%s", loaded.RawContent())
	}
}

func TestLoadContentSupportsAbsoluteTimelineTimes(t *testing.T) {
	input := strings.Join([]string{
		"off: -",
		"ts1: pink/60 750+15/8 500+10/4 350+7/0 100+2/0",
		"ts2: pink/60 750+14/0 500+9/8 350+6/6 100+2/8",
		"00:00:00 off ->",
		"00:00:15 ts1 ->",
		"00:20:00 ts2 ->",
		"00:20:30 off",
	}, "\n")
	loaded, err := LoadContent(input)
	if err != nil {
		t.Fatalf("LoadContent error: %v", err)
	}
	for _, expected := range []string{
		"00:00:00 silence steady 0",
		"00:00:15 ts1 steady 0",
		"00:20:00 ts2 steady 0",
		"00:20:30 silence steady 0",
	} {
		if !strings.Contains(string(loaded.RawContent()), expected) {
			t.Errorf("converted content missing %q:\n%s", expected, loaded.RawContent())
		}
	}
}

func TestLoadFileOmitsMixWithoutMusicOption(t *testing.T) {
	dir := t.TempDir()
	inputPath := filepath.Join(dir, "session.sbg")
	if err := os.WriteFile(inputPath, []byte("alpha: pink/20 mix/20\noff: -\nNOW alpha\n+00:01:00 off\n"), 0o600); err != nil {
		t.Fatalf("write input: %v", err)
	}

	loaded, err := LoadFile(inputPath)
	if err != nil {
		t.Fatalf("LoadFile error: %v", err)
	}
	if strings.Contains(string(loaded.RawContent()), "music") {
		t.Fatalf("mix was not omitted:\n%s", loaded.RawContent())
	}
}
